In [1]:
# Import dependencies
import os 
import csv
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st
import requests

In [2]:
# Data Files
vancouver_01_path = os.path.join("resources/Mobi_System_Data_2019-01.csv")
vancouver_02_path = os.path.join("resources/Mobi_System_Data_2019-02.csv")
vancouver_03_path = os.path.join("resources/Mobi_System_Data_2019-03.csv")
vancouver_04_path = os.path.join("resources/Mobi_System_Data_2019-04.csv")
vancouver_05_path = os.path.join("resources/Mobi_System_Data_2019-05.csv")
vancouver_06_path = os.path.join("resources/Mobi_System_Data_2019-06.csv")
vancouver_07_path = os.path.join("resources/Mobi_System_Data_2019-07.csv")
vancouver_08_path = os.path.join("resources/Mobi_System_Data_2019-08.csv")
vancouver_09_path = os.path.join("resources/Mobi_System_Data_2019-09.csv")
vancouver_10_path = os.path.join("resources/Mobi_System_Data_2019-10.csv")
vancouver_11_path = os.path.join("resources/Mobi_System_Data_2019-11.csv")
vancouver_12_path = os.path.join("resources/Mobi_System_Data_2019-12.csv")

# Read Data Files 
vancouver_01 = pd.read_csv(vancouver_01_path, encoding="utf=8")
vancouver_02 = pd.read_csv(vancouver_02_path, encoding="utf=8")
vancouver_03 = pd.read_csv(vancouver_03_path, encoding="utf=8")
vancouver_04 = pd.read_csv(vancouver_04_path, encoding="utf=8")
vancouver_05 = pd.read_csv(vancouver_05_path, encoding="utf=8")
vancouver_06 = pd.read_csv(vancouver_06_path, encoding="utf=8")
vancouver_07 = pd.read_csv(vancouver_07_path, encoding="utf=8")
vancouver_08 = pd.read_csv(vancouver_08_path, encoding="utf=8")
vancouver_09 = pd.read_csv(vancouver_09_path, encoding="utf=8")
vancouver_10 = pd.read_csv(vancouver_10_path, encoding="utf=8")
vancouver_11 = pd.read_csv(vancouver_11_path, encoding="utf=8")
vancouver_12 = pd.read_csv(vancouver_12_path, encoding="utf=8")

# Combine Data into Quarters (Q1. Q2, Q3, Q4)
q1 = pd.concat([vancouver_01, vancouver_02, vancouver_03], ignore_index=True)
q2 = pd.concat([vancouver_04, vancouver_05, vancouver_06], ignore_index=True)
q3 = pd.concat([vancouver_07, vancouver_08, vancouver_09], ignore_index=True)
q4 = pd.concat([vancouver_10, vancouver_11, vancouver_12], ignore_index=True)

In [3]:
# Display Data Table for Preview - Q1
q1

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (C),Return temperature (C),Stopover duration,Number of stopovers,Manager,Membership Type,Stopover duration (sec.)
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,714.0,177,3826,4000,9,9,0.0,0,False,NaN,NaN
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,859.0,221,3705,3850,9,11,0.0,0,False,NaN,NaN
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,6691.0,3272,3842,4059,10,11,370.0,1,False,NaN,NaN
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,473.0,157,4029,4140,9,10,0.0,0,False,NaN,NaN
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,1404.0,516,3990,4100,9,10,0.0,0,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120307,4/1/2019 0:00,4/1/2019 0:00,1063.0,0119 3rd & Quebec,0150 Alexander & Main,Vancity Community Pass,2093.0,676,3882,4021,12,14,NaN,0,False,NaN,0.0
120308,4/1/2019 0:00,4/1/2019 1:00,1067.0,0050 Bute & Comox,0096 Nicola & Robson,365 Day Founding Plus,5701.0,2908,4037,4253,12,13,NaN,4,False,NaN,1288.0
120309,4/1/2019 0:00,4/1/2019 1:00,1016.0,0096 Nicola & Robson,0088 Harwood & Bute,365 Plus,4935.0,2209,4011,4190,10,14,NaN,0,False,NaN,0.0
120310,4/1/2019 0:00,4/1/2019 0:00,786.0,0002 Burrard Station,0237 Glen & 6th,365 Day Pass Standard SALE,4559.0,1325,3908,4169,13,12,NaN,0,False,NaN,0.0
120311,4/1/2019 0:00,4/1/2019 0:00,37.0,0119 3rd & Quebec,0108 1st & Chestnut,365 Corporate Standard,4384.0,1195,3929,4171,12,13,NaN,0,False,NaN,0.0

In [4]:
# Display Data Table for Preview - Q2
q2

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (C),Return temperature (C),Departure slot,Return slot,Stopover duration (sec.),Number of bike stopovers,Number of stopovers
0,4/30/19 23:51,4/30/19 23:57,179.0,0039 Helmcken & Burrard,0032 Comox & Denman,365 Day Founding Standard,1368.0,329,3810,3937,14,17,3.0,18.0,0,0.0,NaN
1,4/30/19 23:47,4/30/19 23:50,961.0,0187 Bute & Davie,0060 Bidwell & Burnaby,365 Day Pass Standard SALE,904.0,198,3942,4043,14,16,1.0,23.0,0,0.0,NaN
2,4/30/19 23:45,5/1/19 0:39,834.0,0125 Hamilton & Robson,0064 Expo & Smithe,365 Day Founding Plus,4253.0,3238,3768,3897,15,15,1.0,6.0,1929,3.0,NaN
3,4/30/19 23:42,4/30/19 23:50,1535.0,0044 Pacific & Richards,0028 Davie & Beach,30 Day Pass,2068.0,456,3848,3956,16,18,13.0,28.0,0,0.0,NaN
4,4/30/19 23:39,4/30/19 23:49,307.0,0028 Davie & Beach,0002 Burrard Station,365 Day Founding Plus,2442.0,575,3942,4092,12,15,29.0,24.0,0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261535,7/1/2019 0:00,7/1/2019 0:00,730.0,0177 Quebec & 1st,0167 Cordova & Columbia,365 Corporate Plus,1596.0,480,3950,4095,20,20,NaN,NaN,0,NaN,0.0
261536,7/1/2019 0:00,7/1/2019 0:00,1186.0,0255 18th & Main,0235 Charles & Commercial,365 Corporate Plus,4533.0,1258,3956,4145,18,20,NaN,NaN,0,NaN,0.0
261537,7/1/2019 0:00,7/1/2019 0:00,458.0,0110 5th & Arbutus,0110 5th & Arbutus,30 Day Pass,0.0,16,3750,3810,17,16,NaN,NaN,0,NaN,0.0
261538,7/1/2019 0:00,7/1/2019 0:00,2161.0,0126 Thurlow & Pendrell,0055 Keefer & Columbia,365 Day Pass Plus SALE,3553.0,1269,3930,3763,20,21,NaN,NaN,0,NaN,0.0
261539,7/1/2019 0:00,7/1/2019 0:00,961.0,0255 18th & Main,0235 Charles & Commercial,365 Plus,4557.0,1192,3977,4137,18,20,NaN,NaN,0,NaN,0.0

In [5]:
# Display Data Table for Preview - Q3
q3

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (°C),Return temperature (°C),Stopover duration (sec.),Number of stopovers,Departure temperature (C),Return temperature (C)
0,8/1/2019 0:00,8/1/2019 0:00,244.0,0060 Bidwell & Burnaby,0172 10th & Columbia,VIP,5880.0,1329,4082,4308,21.0,21.0,0,0,NaN,NaN
1,8/1/2019 0:00,8/1/2019 0:00,1278.0,0088 Harwood & Bute,0204 York & Yew,365 Corporate Plus,2483.0,627,4050,4155,21.0,23.0,0,0,NaN,NaN
2,8/1/2019 0:00,8/1/2019 0:00,296.0,0027 Beatty & Nelson,0078 Nelson & Mainland,30 Day Pass,465.0,1325,4001,4030,21.0,21.0,0,0,NaN,NaN
3,8/1/2019 0:00,8/1/2019 0:00,1700.0,0027 Beatty & Nelson,0078 Nelson & Mainland,30 Day Pass,496.0,1368,4072,4085,22.0,22.0,19,1,NaN,NaN
4,8/1/2019 0:00,8/1/2019 0:00,414.0,0207 Alberni & Jervis,0047 Chilco & Beach,365 Plus,1772.0,419,4095,4193,21.0,23.0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357566,2019-09-01 0:00,2019-09-01 1:00,1900.0,0064 Expo & Smithe,0064 Expo & Smithe,365 Standard,2672.0,1615,3971,4016,NaN,NaN,0,0,22.0,24.0
357567,2019-09-01 0:00,2019-09-01 0:00,2034.0,0071 14th & Granville,0070 10th & Granville,365 Standard,449.0,120,3932,3958,NaN,NaN,0,0,21.0,22.0
357568,2019-09-01 0:00,2019-09-01 0:00,365.0,0002 Burrard Station,0237 Glen & 6th,365 Corporate Standard,4659.0,1451,4003,4167,NaN,NaN,0,0,21.0,24.0
357569,2019-09-01 0:00,2019-09-01 0:00,1076.0,0040 Cardero & Pendrell,0041 Cardero & Robson,30 Day Pass,624.0,251,4000,4088,NaN,NaN,0,0,20.0,22.0
357570,2019-09-01 0:00,2019-09-01 0:00,769.0,0021 Cordova & Granville,0174 1st & Manitoba,365 Corporate Plus,2609.0,582,3947,4059,NaN,NaN,0,0,22.0,24.0

In [6]:
# Display Data Table for Preview - Q4
q4

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),...,Return temperature (C),Stopover duration (sec.),Number of stopovers,Departure slot,Return slot,Membership Type,Departure temperature (°C),Return temperature (Â°C),Number of bike stopovers,Manager
0,2019-11-01 0:00,2019-11-01 0:00,1464.0,0004 Yaletown-Roundhouse Station,0030 Abbott & Cordova,365 Day Founding Plus,1872.0,587,3982.0,4117.0,...,9.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-11-01 0:00,2019-11-01 0:00,589.0,0004 Yaletown-Roundhouse Station,0050 Bute & Comox,365 Day Founding Standard,1457.0,626,3879.0,4003.0,...,8.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-11-01 0:00,2019-11-01 0:00,217.0,0004 Yaletown-Roundhouse Station,0096 Nicola & Robson,365 Standard,2211.0,814,4016.0,4103.0,...,10.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-11-01 0:00,2019-11-01 0:00,391.0,0099 Vancouver Art Gallery - North Plaza,0099 Vancouver Art Gallery - North Plaza,365 Standard,6.0,116,3629.0,3724.0,...,8.0,15,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-11-01 0:00,2019-11-01 0:00,1692.0,0177 Quebec & 1st,0108 1st & Chestnut,30 Day Pass,3755.0,1098,3947.0,4106.0,...,7.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152338,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,NaN,1084.0,327,3835.0,4076.0,...,NaN,0,NaN,NaN,NaN,30 Day Pass,1.0,2.0,0.0,False
152339,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,NaN,4192.0,1473,3802.0,3908.0,...,NaN,0,NaN,NaN,NaN,365 Standard,4.0,2.0,0.0,False
152340,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,NaN,1292.0,358,3940.0,4088.0,...,NaN,0,NaN,NaN,NaN,365 Day Founding Standard,3.0,5.0,0.0,False
152341,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,NaN,602.0,163,3895.0,4053.0,...,NaN,0,NaN,NaN,NaN,365 Plus,0.0,2.0,0.0,False
152342,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,NaN,608.0,167,3855.0,3926.0,...,NaN,0,NaN,NaN,NaN,365 Plus,1.0,2.0,0.0,False

In [7]:
# Summary Metrics Data Frame
# Total Trips
q1_total = q1.count()["Bike"]
q2_total = q2.count()["Bike"]
q3_total = q3.count()["Bike"]
q4_total = q4.count()["Bike"]

total_trips = q1_total + q2_total + q3_total + q4_total
total_trips

print(q1_total, q2_total, q3_total, q4_total, total_trips)

120308 261536 357251 152139 891234

In [8]:
# Summary Metrics Data Frame
# Station IDs in Q1
q1_uniq_start = q1["Departure station"].nunique() 
q1_uniq_start
q1_uniq_end= q1["Return station"].nunique()
q1_uniq_end

186

In [9]:
# Station IDs in Q2
q2_uniq_start = q2["Departure station"].nunique() 
q2_uniq_end= q2["Return station"].nunique()
q2_uniq_start
q2_uniq_end

196

In [10]:
# Station IDs in Q3
q3_uniq_start = q3["Departure station"].nunique() 
q3_uniq_end= q3["Return station"].nunique()
q3_uniq_start
q3_uniq_end

203

In [11]:
# Station IDs in Q4
q4_uniq_start = q4["Departure station"].nunique() 
q4_uniq_end= q4["Return station"].nunique()
q4_uniq_start
q4_uniq_end

208

In [12]:
# Summary Metrics Data Frame
# All Station IDs in Q1

q1_start_stn = q1["Departure station"]
q1_end_stn = q1["Return station"]
vancouver_stations = []

In [13]:
# Total Unique Stations in Q1
for x in range(len(q1)):
    station = q1_start_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

for x in range(len(q1)):
    station = q1_end_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

In [14]:
len(vancouver_stations)

187

In [15]:
# All Station IDs in Q2 (blocked until above error code is resolved)

q2_start_stn = q2["Departure station"]
q2_end_stn = q2["Return station"]
vancouver_stations = []

In [16]:
# Total Unique Stations in Q2
for x in range(len(q2)):
    station = q2_start_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

for x in range(len(q2)):
    station = q2_end_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

In [17]:
len(vancouver_stations)

197

In [18]:
# All Station IDs in Q3 (blocked until above error code is resolved)

q3_start_stn = q3["Departure station"]
q3_end_stn = q3["Return station"]
vancouver_stations = []

In [19]:
# Total Unique Stations in Q3
for x in range(len(q3)):
    station = q3_start_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

for x in range(len(q3)):
    station = q3_end_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

In [20]:
len(vancouver_stations)

205

In [21]:
# All Station IDs in Q4 (blocked until above error code is resolved)

q4_start_stn = q4["Departure station"]
q4_end_stn = q4["Return station"]
vancouver_stations = []

In [22]:
# Total Unique Stations in Q4     
for x in range(len(q4)):
    station = q4_start_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

for x in range(len(q4)):
    station = q4_end_stn[x]
    if station not in vancouver_stations:
        vancouver_stations.append(station)

In [23]:
len(vancouver_stations)

209

In [ ]:
# Summary Metrics Data Frame
# Total Number of Subscription Users in Q1, Q2, Q3, Q3, Q4

# Only data availble is the "Membership type" column. 
#There is no separate data like the toronto dataset

In [24]:
# Summary Metrics Data Frame
# Total Number fo Casual vs. Annual Members (usertype) 
# in Q1, Q2, Q3, Q3, Q4
user_type = q1[["Membership type"]].drop_duplicates()
user_type_df = pd.DataFrame({"Total Count" : user_type["Membership type"].value_counts()})
user_type_df

user_type = q2[["Membership type"]].drop_duplicates()
user_type_df = pd.DataFrame({"Total Count" : user_type["Membership type"].value_counts()})
user_type_df

user_type = q3[["Membership type"]].drop_duplicates()
user_type_df = pd.DataFrame({"Total Count" : user_type["Membership type"].value_counts()})
user_type_df

user_type = q4[["Membership type"]].drop_duplicates()
user_type_df = pd.DataFrame({"Total Count" : user_type["Membership type"].value_counts()})
user_type_df

                                Total Count
Archived Monthly Standard                 1
Archived Monthly Basic                    1
365 Corporate Standard                    1
Archived Monthly Plus                     1
365 Corporate Plus Renewal                1
Shared Mobility Pass                      1
24 Hour                                   1
365 Corporate Plus                        1
365 Plus                                  1
365 Day Founding Plus                     1
30 Day Pass                               1
VIP                                       1
365 Corporate Standard Renewal            1
365 Day Founding Standard                 1
Vancity Community Pass                    1
365 Day Pass Plus SALE                    1
Archived 90 Day                           1
365 Day Pass Standard SALE                1
365 Standard                              1

In [25]:
# Summary Metrics Data Frame
# Average Trip Duration in Q1, Q2, Q3, Q3, Q4
trip_duration = q1["Duration (sec.)"].mean()
avg_trip_duration = trip_duration / 60

In [26]:
q1

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (C),Return temperature (C),Stopover duration,Number of stopovers,Manager,Membership Type,Stopover duration (sec.)
0,2/1/2019 0:00,2/1/2019 0:00,388.0,0198 6th & Main,0298 6th & Carolina,365 Standard,714.0,177,3826,4000,9,9,0.0,0,False,NaN,NaN
1,2/1/2019 0:00,2/1/2019 0:00,1880.0,0193 Science World,0173 1st & Columbia,365 Plus,859.0,221,3705,3850,9,11,0.0,0,False,NaN,NaN
2,2/1/2019 0:00,2/1/2019 0:00,779.0,0063 Robson & Granville,0143 South False Creek Seawall,Vancity Community Pass,6691.0,3272,3842,4059,10,11,370.0,1,False,NaN,NaN
3,2/1/2019 0:00,2/1/2019 0:00,2123.0,0064 Expo & Smithe,0078 Nelson & Mainland,365 Day Pass Plus SALE,473.0,157,4029,4140,9,10,0.0,0,False,NaN,NaN
4,1/31/2019 23:00,2/1/2019 0:00,444.0,0060 Bidwell & Burnaby,0196 Drake & Hornby,365 Day Pass Plus SALE,1404.0,516,3990,4100,9,10,0.0,0,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120307,4/1/2019 0:00,4/1/2019 0:00,1063.0,0119 3rd & Quebec,0150 Alexander & Main,Vancity Community Pass,2093.0,676,3882,4021,12,14,NaN,0,False,NaN,0.0
120308,4/1/2019 0:00,4/1/2019 1:00,1067.0,0050 Bute & Comox,0096 Nicola & Robson,365 Day Founding Plus,5701.0,2908,4037,4253,12,13,NaN,4,False,NaN,1288.0
120309,4/1/2019 0:00,4/1/2019 1:00,1016.0,0096 Nicola & Robson,0088 Harwood & Bute,365 Plus,4935.0,2209,4011,4190,10,14,NaN,0,False,NaN,0.0
120310,4/1/2019 0:00,4/1/2019 0:00,786.0,0002 Burrard Station,0237 Glen & 6th,365 Day Pass Standard SALE,4559.0,1325,3908,4169,13,12,NaN,0,False,NaN,0.0
120311,4/1/2019 0:00,4/1/2019 0:00,37.0,0119 3rd & Quebec,0108 1st & Chestnut,365 Corporate Standard,4384.0,1195,3929,4171,12,13,NaN,0,False,NaN,0.0

In [27]:
trip_duration = q2["Duration (sec.)"].mean()
avg_trip_duration = trip_duration / 60

In [28]:
q2

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (C),Return temperature (C),Departure slot,Return slot,Stopover duration (sec.),Number of bike stopovers,Number of stopovers
0,4/30/19 23:51,4/30/19 23:57,179.0,0039 Helmcken & Burrard,0032 Comox & Denman,365 Day Founding Standard,1368.0,329,3810,3937,14,17,3.0,18.0,0,0.0,NaN
1,4/30/19 23:47,4/30/19 23:50,961.0,0187 Bute & Davie,0060 Bidwell & Burnaby,365 Day Pass Standard SALE,904.0,198,3942,4043,14,16,1.0,23.0,0,0.0,NaN
2,4/30/19 23:45,5/1/19 0:39,834.0,0125 Hamilton & Robson,0064 Expo & Smithe,365 Day Founding Plus,4253.0,3238,3768,3897,15,15,1.0,6.0,1929,3.0,NaN
3,4/30/19 23:42,4/30/19 23:50,1535.0,0044 Pacific & Richards,0028 Davie & Beach,30 Day Pass,2068.0,456,3848,3956,16,18,13.0,28.0,0,0.0,NaN
4,4/30/19 23:39,4/30/19 23:49,307.0,0028 Davie & Beach,0002 Burrard Station,365 Day Founding Plus,2442.0,575,3942,4092,12,15,29.0,24.0,0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261535,7/1/2019 0:00,7/1/2019 0:00,730.0,0177 Quebec & 1st,0167 Cordova & Columbia,365 Corporate Plus,1596.0,480,3950,4095,20,20,NaN,NaN,0,NaN,0.0
261536,7/1/2019 0:00,7/1/2019 0:00,1186.0,0255 18th & Main,0235 Charles & Commercial,365 Corporate Plus,4533.0,1258,3956,4145,18,20,NaN,NaN,0,NaN,0.0
261537,7/1/2019 0:00,7/1/2019 0:00,458.0,0110 5th & Arbutus,0110 5th & Arbutus,30 Day Pass,0.0,16,3750,3810,17,16,NaN,NaN,0,NaN,0.0
261538,7/1/2019 0:00,7/1/2019 0:00,2161.0,0126 Thurlow & Pendrell,0055 Keefer & Columbia,365 Day Pass Plus SALE,3553.0,1269,3930,3763,20,21,NaN,NaN,0,NaN,0.0
261539,7/1/2019 0:00,7/1/2019 0:00,961.0,0255 18th & Main,0235 Charles & Commercial,365 Plus,4557.0,1192,3977,4137,18,20,NaN,NaN,0,NaN,0.0

In [29]:
trip_duration = q3["Duration (sec.)"].mean()
avg_trip_duration = trip_duration / 60

In [30]:
q3

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),Departure temperature (°C),Return temperature (°C),Stopover duration (sec.),Number of stopovers,Departure temperature (C),Return temperature (C)
0,8/1/2019 0:00,8/1/2019 0:00,244.0,0060 Bidwell & Burnaby,0172 10th & Columbia,VIP,5880.0,1329,4082,4308,21.0,21.0,0,0,NaN,NaN
1,8/1/2019 0:00,8/1/2019 0:00,1278.0,0088 Harwood & Bute,0204 York & Yew,365 Corporate Plus,2483.0,627,4050,4155,21.0,23.0,0,0,NaN,NaN
2,8/1/2019 0:00,8/1/2019 0:00,296.0,0027 Beatty & Nelson,0078 Nelson & Mainland,30 Day Pass,465.0,1325,4001,4030,21.0,21.0,0,0,NaN,NaN
3,8/1/2019 0:00,8/1/2019 0:00,1700.0,0027 Beatty & Nelson,0078 Nelson & Mainland,30 Day Pass,496.0,1368,4072,4085,22.0,22.0,19,1,NaN,NaN
4,8/1/2019 0:00,8/1/2019 0:00,414.0,0207 Alberni & Jervis,0047 Chilco & Beach,365 Plus,1772.0,419,4095,4193,21.0,23.0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357566,2019-09-01 0:00,2019-09-01 1:00,1900.0,0064 Expo & Smithe,0064 Expo & Smithe,365 Standard,2672.0,1615,3971,4016,NaN,NaN,0,0,22.0,24.0
357567,2019-09-01 0:00,2019-09-01 0:00,2034.0,0071 14th & Granville,0070 10th & Granville,365 Standard,449.0,120,3932,3958,NaN,NaN,0,0,21.0,22.0
357568,2019-09-01 0:00,2019-09-01 0:00,365.0,0002 Burrard Station,0237 Glen & 6th,365 Corporate Standard,4659.0,1451,4003,4167,NaN,NaN,0,0,21.0,24.0
357569,2019-09-01 0:00,2019-09-01 0:00,1076.0,0040 Cardero & Pendrell,0041 Cardero & Robson,30 Day Pass,624.0,251,4000,4088,NaN,NaN,0,0,20.0,22.0
357570,2019-09-01 0:00,2019-09-01 0:00,769.0,0021 Cordova & Granville,0174 1st & Manitoba,365 Corporate Plus,2609.0,582,3947,4059,NaN,NaN,0,0,22.0,24.0

In [31]:
trip_duration = q4["Duration (sec.)"].mean()
avg_trip_duration = trip_duration / 60

In [32]:
q4

,Departure,Return,Bike,Departure station,Return station,Membership type,Covered distance (m),Duration (sec.),Departure battery voltage (mV),Return battery voltage (mV),...,Return temperature (C),Stopover duration (sec.),Number of stopovers,Departure slot,Return slot,Membership Type,Departure temperature (°C),Return temperature (Â°C),Number of bike stopovers,Manager
0,2019-11-01 0:00,2019-11-01 0:00,1464.0,0004 Yaletown-Roundhouse Station,0030 Abbott & Cordova,365 Day Founding Plus,1872.0,587,3982.0,4117.0,...,9.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-11-01 0:00,2019-11-01 0:00,589.0,0004 Yaletown-Roundhouse Station,0050 Bute & Comox,365 Day Founding Standard,1457.0,626,3879.0,4003.0,...,8.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-11-01 0:00,2019-11-01 0:00,217.0,0004 Yaletown-Roundhouse Station,0096 Nicola & Robson,365 Standard,2211.0,814,4016.0,4103.0,...,10.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-11-01 0:00,2019-11-01 0:00,391.0,0099 Vancouver Art Gallery - North Plaza,0099 Vancouver Art Gallery - North Plaza,365 Standard,6.0,116,3629.0,3724.0,...,8.0,15,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-11-01 0:00,2019-11-01 0:00,1692.0,0177 Quebec & 1st,0108 1st & Chestnut,30 Day Pass,3755.0,1098,3947.0,4106.0,...,7.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152338,2019-12-01 0:00,2019-12-01 0:00,631.0,0187 Bute & Davie,0032 Comox & Denman,NaN,1084.0,327,3835.0,4076.0,...,NaN,0,NaN,NaN,NaN,30 Day Pass,1.0,2.0,0.0,False
152339,2019-12-01 0:00,2019-12-01 1:00,1394.0,0024 Hornby & Pender,0208 Arbutus Greenway & Broadway,NaN,4192.0,1473,3802.0,3908.0,...,NaN,0,NaN,NaN,NaN,365 Standard,4.0,2.0,0.0,False
152340,2019-12-01 0:00,2019-12-01 0:00,1511.0,0099 Vancouver Art Gallery - North Plaza,0096 Nicola & Robson,NaN,1292.0,358,3940.0,4088.0,...,NaN,0,NaN,NaN,NaN,365 Day Founding Standard,3.0,5.0,0.0,False
152341,2019-12-01 0:00,2019-12-01 0:00,985.0,0193 Science World,0174 1st & Manitoba,NaN,602.0,163,3895.0,4053.0,...,NaN,0,NaN,NaN,NaN,365 Plus,0.0,2.0,0.0,False
152342,2019-12-01 0:00,2019-12-01 0:00,291.0,0193 Science World,0174 1st & Manitoba,NaN,608.0,167,3855.0,3926.0,...,NaN,0,NaN,NaN,NaN,365 Plus,1.0,2.0,0.0,False

In [ ]:
# Summary Metrics Data Frame
# Bins (Max & Min) in Q1, Q2, Q3, Q3, Q4

# i am not too confident with this, 
#so if its alright can we do this together